// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package org.lambda.model;

import org.lambda.model.Employee.Title;

public class EmployeeBuilder extends
		EmployeeBuilderBase<EmployeeBuilder> {
	public static EmployeeBuilder employee() {
		return new EmployeeBuilder();
	}

	public EmployeeBuilder() {
		super(new Employee());
	}

	public Employee build() {
		return getInstance();
	}
}

class EmployeeBuilderBase<GeneratorT extends EmployeeBuilderBase<GeneratorT>> {
	private Employee instance;

	protected EmployeeBuilderBase(Employee aInstance) {
		instance = aInstance;
	}

	protected Employee getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTitle(Title aValue) {
		instance.setTitle(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withFirstName(String aValue) {
		instance.setFirstName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withLastName(String aValue) {
		instance.setLastName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPersonnelNumber(int aValue) {
		instance.setPersonnelNumber(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withYearsOfExperience(int aValue) {
		instance.setYearsOfExperience(aValue);

		return (GeneratorT) this;
	}
}
